# Generated by Django 4.2.4 on 2023-10-17 10:06

import django.contrib.auth.models
from django.db import migrations, models
import taskmangement.users.manager
import taskmangement.utilities.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("object", taskmangement.users.manager.UserManager()),
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="user",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name="metaadata"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(db_index=True, max_length=225, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.CharField(
                default=taskmangement.utilities.utils.generate_id, max_length=255, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="Name"),
        ),
    ]
