# Generated by Django 4.2.4 on 2023-10-18 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taskmangement.utilities.utils


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        ("users", "0003_user_created_at_user_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=taskmangement.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="Name")),
                ("email", models.CharField(db_index=True, max_length=225, unique=True, verbose_name="Email")),
                ("location", models.CharField(db_index=True, max_length=225, unique=True, verbose_name="Location")),
                ("country", models.CharField(db_index=True, max_length=225, unique=True, verbose_name="Country")),
                (
                    "postal_code",
                    models.CharField(db_index=True, max_length=225, unique=True, verbose_name="Postal_Code"),
                ),
                (
                    "description",
                    models.TextField(db_index=True, max_length=500, unique=True, verbose_name="Description"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict, null=True, verbose_name="metaadata")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_ceo",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teams",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organization_teams",
                        to="tasks.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
