# Generated by Django 4.2.4 on 2023-10-18 05:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_can_admin_alter_organization_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="can_admin",
            new_name="is_organization_admin",
        ),
    ]
