# Generated by Django 4.2.4 on 2023-10-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_can_admin_user_is_organization_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_organization_staff",
            field=models.BooleanField(default=False, verbose_name="is_staff"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is_active"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_organization_admin",
            field=models.BooleanField(default=False, verbose_name="is_admin"),
        ),
    ]
