# Generated by Django 4.2.4 on 2023-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
        ("users", "0007_user_is_organization_staff_alter_user_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="teams",
        ),
        migrations.AddField(
            model_name="organization",
            name="teams",
            field=models.ManyToManyField(
                blank=True, db_index=True, related_name="organization_teams", to="tasks.team"
            ),
        ),
    ]
