# Generated by Django 4.2.4 on 2023-10-18 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taskmangement.utilities.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActionPoint",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=taskmangement.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("blocker", models.TextField(db_index=True, max_length=500, unique=True, verbose_name="Blocker")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("STARTED", "Started"),
                            ("ONGOING", "Ongoing"),
                            ("STUCK", "Stuck"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=50,
                        verbose_name="Status",
                    ),
                ),
                ("reviewed", models.BooleanField(db_index=True, default=False, verbose_name="Reviewed")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Collaborate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=taskmangement.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("title", models.CharField(db_index=True, max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(db_index=True, max_length=500, unique=True, verbose_name="Description"),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[("HIGH", "High"), ("URGENT", "Urgent"), ("CRITICAL", "Critical"), ("ASAP", "Asap")],
                        db_index=True,
                        default="HIGH",
                        max_length=50,
                        verbose_name="urgency_level",
                    ),
                ),
                ("deadline", models.DateTimeField(db_index=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collabo_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=taskmangement.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("name", models.CharField(db_index=True, max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(db_index=True, max_length=500, unique=True, verbose_name="Description"),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_lead",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, db_index=True, related_name="team_members", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=taskmangement.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                ("title", models.CharField(db_index=True, max_length=255, verbose_name="title")),
                (
                    "description",
                    models.TextField(db_index=True, max_length=500, unique=True, verbose_name="Description"),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[("HIGH", "High"), ("URGENT", "Urgent"), ("CRITICAL", "Critical"), ("ASAP", "Asap")],
                        db_index=True,
                        default="HIGH",
                        max_length=50,
                        verbose_name="urgency_level",
                    ),
                ),
                ("deadline", models.DateTimeField(db_index=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True, db_index=True, related_name="task_created_to", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.collaborate"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=taskmangement.utilities.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("active", models.BooleanField(db_index=True, default=True, verbose_name="active")),
                (
                    "suggestion",
                    models.TextField(db_index=True, max_length=500, unique=True, verbose_name="Suggestion"),
                ),
                ("approved", models.BooleanField(db_index=True, default=False, verbose_name="Approved")),
                (
                    "action_point",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.actionpoint"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collaborate",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True, db_index=True, related_name="collabo_created_for", to="tasks.team"
            ),
        ),
        migrations.AddField(
            model_name="collaborate",
            name="owner",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="actionpoint",
            name="task",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="tasks.task"
            ),
        ),
    ]
